import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Polo Slim shirt',
      slug: 'polo-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Whiskas Chicken',
      slug: 'whiskas-kitten',
      animal: 'Cats',
      category: 'Food',
      image: '/images/p4.jpg',
      price: 265,
      countInStock: 5,
      brand: 'Knorr',
      rating: 4.5,
      numReviews: 10,
      description: 'chicken jelly for kittens.',
    },
    {
      // _id: '6',
      name: 'Jumbo Bisquit',
      slug: 'jumbo-puppy',
      animal: 'Dogs',
      category: 'Food',
      image: '/images/p4.jpg',
      price: 230,
      countInStock: 5,
      brand: 'Jelow',
      rating: 4.5,
      numReviews: 10,
      description: 'bisquits for dogs',
    },
    {
      // _id: '7',
      name: 'Pink Collar',
      slug: 'pink-collar',
      animal: 'Cats',
      category: 'Collar',
      image: '/images/p4.jpg',
      price: 40,
      countInStock: 5,
      brand: 'Crusser',
      rating: 4.5,
      numReviews: 10,
      description: 'cute pink collar for kitten',
    },
    {
      // _id: '8',
      name: 'Yellow Collar',
      slug: 'collar-yellow',
      animal: 'Dogs',
      category: 'Collar',
      image: '/images/p4.jpg',
      price: 50,
      countInStock: 5,
      brand: 'Crusser',
      rating: 4.5,
      numReviews: 10,
      description: 'pretty yellow collar for puppies',
    },
  ],
};
export default data;
